Added emojies to the comment diff part
ScaCap/code-coverage-assistant pull request #19
Opened 2020-12-18 10:03 UTC by marinakalyuzhnaya

2020-12-18 12:00 UTC, Weetbix approved these changes
Looks great, saw it in action with your other PR

2020-12-18 12:00 UTC, Weetbix commented on src/comment.js
> +	if (pdiff > 0) return "🟢";
Lets use `>= 0` here, so that we always have an emoji and that 0% shows as green :)

2020-12-18 12:33 UTC, eeshdarthvader approved these changes
Nice

2021-02-05 14:47 UTC, janory approved these changes
LGTM! 👍

2021-02-09 10:01 UTC, Weetbix approved these changes
Looks great again, I've seen it in action :)

2021-02-09 10:08 UTC, eeshdarthvader requested changes
Looks good. Few changes added.

2021-02-09 10:08 UTC, eeshdarthvader commented on action.yml
> +    description: The concrete app name to dispaly on comment
```suggestion
    description: App name to display on comment
```

2021-02-09 10:08 UTC, eeshdarthvader commented on dist/main.js
> +    if (pdiff >= 0) return "🟢";
```suggestion
    if (pdiff < 0) return "🔴";
    return "🟢";
```

2021-02-09 10:08 UTC, eeshdarthvader commented on dist/main.js
> +				hiddenHeader: appName ? `<!-- ${appName}-jest-reporter-action -->` : `<!-- monorepo-jest-reporter-action -->`
```suggestion
				hiddenHeader: appName ? `<!-- ${appName}-code-coverage-assistant-action -->` : `<!-- monorepo-code-coverage-assistant-action -->`
```

2021-02-09 10:08 UTC, eeshdarthvader commented on src/comment.js
> +    if (pdiff >= 0) return "🟢";
```suggestion
    if (pdiff < 0) return "🔴";
     return "🟢";
```

2021-02-09 10:30 UTC, eeshdarthvader commented on dist/main.js
> +    return "🟢";
shouldn't this be green filled circle ?

2021-02-09 10:30 UTC, marinakalyuzhnaya commented
> Looks great again, I've seen it in action :)

I already have some improvements ideas, how to show only changed lines without having a base file. :)

2021-02-09 10:31 UTC, marinakalyuzhnaya commented on dist/main.js
> +    return "🟢";
I do not get the question

2021-02-09 10:55 UTC, eeshdarthvader approved these changes
Looks great. ❤️

2021-02-09 13:15 UTC, merged